package cmd

import (
	"os"
	"fmt"
	"github.com/spf13/cobra"

	core "github.com/jlkendrick/sigil/core"
	types "github.com/jlkendrick/sigil/types"
)

func GenerateCommands(config *types.Config) ([]*cobra.Command, error) {
	commands := []*cobra.Command{}

	for _, function := range config.Functions {
		command := &cobra.Command{
			Use: function.Name,
			Run: func(cmd *cobra.Command, args []string) {
				payload := buildPayload(function, cmd)

				result, err := core.ExecuteFunction(function, payload)
				if err != nil {
					fmt.Printf("Error executing function: %v\n", err)
					os.Exit(1)
				}

				fmt.Println(string(result))
			},
		}

		for _, arg := range function.Args {
			// Types might be wrong here if not generated by the init command, but we just assume the user knows what they're doing.
			// We do need to check if the default value corresponds to the type and give a helpful error message if not.
			switch arg.Type {
			case "string":
				if _, ok := arg.Default.(string); !ok {
					return nil, fmt.Errorf("default value for %s is not a string", arg.Name)
				}
				command.Flags().StringP(arg.Name, "", arg.Default.(string), "")
			case "int":
				if _, ok := arg.Default.(int); !ok {
					return nil, fmt.Errorf("default value for %s is not an int", arg.Name)
				}
				command.Flags().IntP(arg.Name, "", arg.Default.(int), "")
			case "bool":
				if _, ok := arg.Default.(bool); !ok {
					return nil, fmt.Errorf("default value for %s is not a bool", arg.Name)
				}
				command.Flags().BoolP(arg.Name, "", arg.Default.(bool), "")
			case "float":
				if _, ok := arg.Default.(float64); !ok {
					return nil, fmt.Errorf("default value for %s is not a float64", arg.Name)
				}
				command.Flags().Float64P(arg.Name, "", arg.Default.(float64), "")
			default:
				return nil, fmt.Errorf("unsupported type: %s", arg.Type)
			}

			if arg.Default == nil {
				command.MarkFlagRequired(arg.Name)
			}
		}

		commands = append(commands, command)
	}

	return commands, nil
}

func buildPayload(function types.Function, cmd *cobra.Command) map[string]interface{} {
	// Initialize the dynamic payload map
	payload := make(map[string]interface{})

	// Loop through the YAML params for this specific function
	for _, param := range function.Args {
			// Extract from Cobra based on the YAML type
			switch param.Type {
			case "int":
					// Cobra already validated this is an int, so we can safely extract it
					val, _ := cmd.Flags().GetInt(param.Name)
					payload[param.Name] = val
			case "string":
					val, _ := cmd.Flags().GetString(param.Name)
					payload[param.Name] = val
			case "bool":
					val, _ := cmd.Flags().GetBool(param.Name)
					payload[param.Name] = val
			}
	}

	return payload
}