package cmd

import (
	"os"
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"

	descriptor "github.com/jlkendrick/grimoire/internal/descriptor"
	runtime "github.com/jlkendrick/grimoire/internal/runtime"
)

func GenerateCommands(descriptors *[]descriptor.FunctionDescriptor) ([]*cobra.Command, error) {
	commands := []*cobra.Command{}

	for _, descriptor := range *descriptors {
		command := &cobra.Command{
			Use: descriptor.CommandName,
			Run: func(cmd *cobra.Command, args []string) {

				// Pre-run: check if the function descriptor is stale relative to the source code
				

				payload := buildPayload(&descriptor, cmd)

				start := time.Now()
				runResult, err := runtime.Run(&descriptor, payload)
				elapsed := time.Since(start)
				if err != nil {
					fmt.Fprintf(os.Stderr, "Error executing function: %v\n", err)
					os.Exit(1)
				}

				fmt.Println(string(runResult.Output))

				footerParts := []string{fmt.Sprintf("%.2fs", elapsed.Seconds())}
				if runResult.CacheStatus != "" {
					footerParts = append(footerParts, runResult.CacheStatus)
				}
				if runResult.Runtime != "" {
					footerParts = append(footerParts, runResult.Runtime)
				}
				fmt.Fprintf(os.Stderr, "\n%s %s\n", accent_style("◈"), dim_style(strings.Join(footerParts, " · ")))
			},
		}

		for _, param := range descriptor.Params {
			// Types might be wrong here if not generated by the init command, but we just assume the user knows what they're doing.
			// We do need to check if the default value corresponds to the type and give a helpful error message if not.
			switch param.ResolvedType.Kind {

			case "string", "str":
				if param.Default == nil {
					command.Flags().StringP(param.Name, "", "", "")
					command.MarkFlagRequired(param.Name)
					continue
				}
				if _, ok := param.Default.(string); !ok {
					return nil, fmt.Errorf("default value for %s is not a string", param.Name)
				}
				command.Flags().StringP(param.Name, "", param.Default.(string), "")

			case "integer", "int":
				if param.Default == nil {
					command.Flags().IntP(param.Name, "", 0, "")
					command.MarkFlagRequired(param.Name)
					continue
				}
				if _, ok := param.Default.(int); !ok {
					return nil, fmt.Errorf("default value for %s is not an int", param.Name)
				}
				command.Flags().IntP(param.Name, "", param.Default.(int), "")

			case "boolean", "bool":
				if param.Default == nil {
					command.Flags().BoolP(param.Name, "", false, "")
					command.MarkFlagRequired(param.Name)
					continue
				}
				if _, ok := param.Default.(bool); !ok {
					return nil, fmt.Errorf("default value for %s is not a bool", param.Name)
				}
				command.Flags().BoolP(param.Name, "", param.Default.(bool), "")

			case "float":
				if param.Default == nil {
					command.Flags().Float64P(param.Name, "", 0.0, "")
					command.MarkFlagRequired(param.Name)
					continue
				}
				if _, ok := param.Default.(float64); !ok {
					return nil, fmt.Errorf("default value for %s is not a float64", param.Name)
				}
				command.Flags().Float64P(param.Name, "", param.Default.(float64), "")

			default:
				return nil, fmt.Errorf("unsupported type: %s", param.ResolvedType.Kind)
			}
		}

		commands = append(commands, command)
	}

	return commands, nil
}

func buildPayload(descriptor *descriptor.FunctionDescriptor, cmd *cobra.Command) map[string]interface{} {
	// Initialize the dynamic payload map
	payload := make(map[string]interface{})

	// Loop through the YAML params for this specific function
	for _, param := range descriptor.Params {
		// Must match the type strings used in GenerateCommands (including aliases like str/int/bool).
		switch param.ResolvedType.Kind {
		case "integer", "int":
			val, _ := cmd.Flags().GetInt(param.Name)
			payload[param.Name] = val
		case "string", "str":
			val, _ := cmd.Flags().GetString(param.Name)
			payload[param.Name] = val
		case "boolean", "bool":
			val, _ := cmd.Flags().GetBool(param.Name)
			payload[param.Name] = val
		case "float":
			val, _ := cmd.Flags().GetFloat64(param.Name)
			payload[param.Name] = val
		}
	}

	return payload
}