package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cache "github.com/jlkendrick/grimoire/internal/cache"
	descriptor "github.com/jlkendrick/grimoire/internal/descriptor"
	graph "github.com/jlkendrick/grimoire/internal/graph"
	resolve "github.com/jlkendrick/grimoire/internal/resolve"
	runenv "github.com/jlkendrick/grimoire/internal/runenv"
)

// buildFunctionCommand exposes a spell as a CLI command, running it as
// the one-node case of the execution graph (spell node + autogenerated
// print). The cached descriptor supplies the flags; the run handler
// re-resolves through the Env so a changed source file is re-extracted.
//
// Bare spells keep the runtime's own framing (provisioning/casting
// lines) and stream user prints verbatim to stderr — no renderer, no
// spinner: a spell's chatter is often its point (rich panels, progress
// bars). stdout carries only the JSON-encoded return value, and a spell
// that returns nothing prints nothing.
func buildFunctionCommand(function_descriptor descriptor.FunctionDescriptor, descriptor_cache *cache.DescriptorCache, spellIndex *resolve.SpellIndex) (*cobra.Command, error) {
	command := &cobra.Command{
		Use: function_descriptor.CommandName,
		Run: func(cmd *cobra.Command, args []string) {
			var last runenv.FinishInfo
			env := runenv.New(descriptor_cache, spellIndex, runenv.Config{
				Present: presentJSON,
				Framing: true,
				Observer: &runenv.Observer{
					// Only finish is observed — leaving OnSpellStderr
					// unset keeps the verbatim stderr passthrough.
					OnSpellFinish: func(_ int, _ string, res runenv.FinishInfo) { last = res },
				},
			})

			fn, err := env.ResolveSpell(function_descriptor.CommandName)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error resolving spell: %v\n", err)
				os.Exit(1)
			}
			payload, err := buildPayload(*fn, cmd)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error building arguments: %v\n", err)
				os.Exit(1)
			}

			g := graph.BuildFunction(fn, env)
			start := time.Now()
			_, err = graph.Run(context.Background(), g, payload)
			elapsed := time.Since(start)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error executing function: %v\n", err)
				os.Exit(1)
			}

			footerParts := []string{fmt.Sprintf("%.2fs", elapsed.Seconds())}
			if last.CacheStatus != "" {
				footerParts = append(footerParts, last.CacheStatus)
			}
			if last.RuntimeVersion != "" {
				footerParts = append(footerParts, last.RuntimeVersion)
			}
			fmt.Fprintf(os.Stderr, "\n%s %s\n", accent_style("◈"), dim_style(strings.Join(footerParts, " · ")))
		},
	}

	for _, param := range function_descriptor.Params {
		if err := registerParamFlag(command, param); err != nil {
			return nil, err
		}
	}

	return command, nil
}

// presentJSON writes one value as canonical JSON on stdout — the bare
// spell's presenter (rituals present through the renderer instead).
func presentJSON(v any) error {
	data, err := json.Marshal(v)
	if err != nil {
		return err
	}
	fmt.Println(string(data))
	return nil
}
