package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	cache "github.com/jlkendrick/grimoire/internal/cache"
	graph "github.com/jlkendrick/grimoire/internal/graph"
	ir "github.com/jlkendrick/grimoire/internal/ir"
	resolve "github.com/jlkendrick/grimoire/internal/resolve"
	runenv "github.com/jlkendrick/grimoire/internal/runenv"
)

// buildPipelineCommand exposes a ritual as a CLI command. The entry
// spell's params become the command's flags; on run the pipeline is
// compiled to an execution graph and handed to the one scheduler.
//
// stdout discipline: declared prints (and the autogenerated tail-print
// of a linear ritual) are the only thing a ritual writes to stdout —
// `grimoire deploy | jq .url` composes. Spell stderr and the timing
// footer go to stderr. Per-step progress UX (spinner, step counters,
// runtime versions) returns with the observer.
func buildPipelineCommand(pipeline ir.Pipeline, descriptor_cache *cache.DescriptorCache, spellIndex *resolve.SpellIndex) (*cobra.Command, error) {
	if len(pipeline.Steps) == 0 {
		return nil, fmt.Errorf("ritual %s has no steps", pipeline.Command)
	}
	if pipeline.Steps[0].Kind() != "spell" {
		return nil, fmt.Errorf("ritual %s: first step must be a spell (reconciler invariant)", pipeline.Command)
	}

	first_step_descriptor_ptr, err := resolve.ResolveSpellRef(pipeline.Steps[0].Spell, descriptor_cache, spellIndex)
	if err != nil {
		return nil, fmt.Errorf("ritual %s: %v", pipeline.Command, err)
	}
	first_step_descriptor := *first_step_descriptor_ptr

	command := &cobra.Command{
		Use: pipeline.Command,
		Run: func(cmd *cobra.Command, args []string) {
			inputs, err := buildPayload(first_step_descriptor, cmd)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error building arguments: %v\n", err)
				os.Exit(1)
			}

			env := runenv.New(descriptor_cache, spellIndex, presentJSON)
			g, err := graph.BuildPipeline(&pipeline, env)
			if err != nil {
				fmt.Fprintf(os.Stderr, "%v\n", err)
				os.Exit(1)
			}

			start := time.Now()
			if _, err := graph.Run(context.Background(), g, inputs); err != nil {
				fmt.Fprintf(os.Stderr, "%v\n", err)
				os.Exit(1)
			}
			elapsed := time.Since(start)
			fmt.Fprintf(os.Stderr, "\n%s %s\n", accent_style("◈"), dim_style(fmt.Sprintf("%.2fs", elapsed.Seconds())))
		},
	}

	// Forward the entry step's params as flags on the pipeline command, so
	// `grimoire <ritual> --x 4` reaches the first step the same way
	// `grimoire <spell> --x 4` reaches a directly-cast spell. A ritual-level
	// override in the first step's `params:` wins over the spell's own default.
	first_step_overrides := pipeline.Steps[0].Params
	for _, param := range first_step_descriptor.Params {
		if override, ok := first_step_overrides[param.Name]; ok {
			param.Default = override
		}
		if err := registerParamFlag(command, param); err != nil {
			return nil, err
		}
	}

	return command, nil
}

// presentJSON writes one declared output as canonical JSON on stdout.
// Values arrive decoded (they are function return values); re-encoding
// prints objects and strings exactly as the old engine's raw-bytes
// passthrough did.
func presentJSON(v any) error {
	data, err := json.Marshal(v)
	if err != nil {
		return err
	}
	fmt.Println(string(data))
	return nil
}
