package graph

import (
	"context"
	"slices"
	"strings"
	"sync"
	"testing"

	ir "github.com/jlkendrick/grimoire/internal/ir"
)

// fakeCalls records what a built graph did: every spell payload and every
// printed value, in order.
type fakeCalls struct {
	mu       sync.Mutex
	payloads map[string]map[string]any
	prints   []any
}

// fakeEnv wires canned spell outputs (keyed by spell name) into an Env.
// params optionally gives a spell a signature, for chained adaptation.
func fakeEnv(outputs map[string]any, params map[string][]ir.Param, calls *fakeCalls) Env {
	calls.payloads = make(map[string]map[string]any)
	return Env{
		ResolveSpell: func(name string) (*ir.Function, error) {
			return &ir.Function{CommandName: name, Params: params[name]}, nil
		},
		RunSpell: func(_ context.Context, fn *ir.Function, payload map[string]any) (any, error) {
			calls.mu.Lock()
			calls.payloads[fn.CommandName] = payload
			calls.mu.Unlock()
			return outputs[fn.CommandName], nil
		},
		Present: func(v any) error {
			calls.mu.Lock()
			calls.prints = append(calls.prints, v)
			calls.mu.Unlock()
			return nil
		},
	}
}

func mustBuild(t *testing.T, p *ir.Pipeline, env Env) *Graph {
	t.Helper()
	g, err := BuildPipeline(p, env)
	if err != nil {
		t.Fatal(err)
	}
	return g
}

func nodeByID(t *testing.T, g *Graph, id string) *Node {
	t.Helper()
	for _, n := range g.Nodes {
		if n.ID == id {
			return n
		}
	}
	t.Fatalf("node %q not found in %v", id, nodeIDs(g))
	return nil
}

func nodeIDs(g *Graph) []string {
	ids := make([]string, len(g.Nodes))
	for i, n := range g.Nodes {
		ids[i] = n.ID
	}
	return ids
}

func TestBuildPipeline_PipeChainShape(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Steps: []ir.Step{
		{Spell: "a"},
		{Spell: "b", Id: "bee", Params: map[string]any{"x": 1}},
		{Spell: "c"},
	}}, env)

	if len(g.Nodes) != 4 {
		t.Fatalf("nodes = %v, want 3 spells + autogenerated print", nodeIDs(g))
	}
	a, b, c, p := g.Nodes[0], g.Nodes[1], g.Nodes[2], g.Nodes[3]

	if a.Input.Kind != InputSeed || len(a.Deps) != 0 {
		t.Errorf("first node: input %v deps %v, want Seed and no deps", a.Input.Kind, a.Deps)
	}
	if b.ID != "bee" || b.Input.Kind != InputParams || !slices.Equal(b.Deps, []string{a.ID}) {
		t.Errorf("params step: id %q input %v deps %v", b.ID, b.Input.Kind, b.Deps)
	}
	if c.Input.Kind != InputChain || !slices.Equal(c.Deps, []string{"bee"}) {
		t.Errorf("chain step: input %v deps %v", c.Input.Kind, c.Deps)
	}
	if !c.Op.(*SpellOp).Chained || a.Op.(*SpellOp).Chained || b.Op.(*SpellOp).Chained {
		t.Error("Chained must be set exactly on chain-input spells")
	}
	if _, ok := p.Op.(*PrintOp); !ok || g.Out != p.ID || !slices.Equal(p.Deps, []string{c.ID}) {
		t.Errorf("tail: %T deps %v out %q, want auto-print chained to c", p.Op, p.Deps, g.Out)
	}
}

func TestBuildPipeline_BranchEntrySpellAdaptsChained(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Steps: []ir.Step{
		{Id: "check", Spell: "status"},
		{If: "check.ok", Then: []ir.Step{{Spell: "handle"}}},
	}}, env)

	// The root entry takes the flags payload directly; a branch entry's
	// seed is an upstream return value, so a no-params branch entry must
	// adapt it like a chained input (a zero-param spell gets {}, not the
	// whole upstream map as kwargs).
	if g.Nodes[0].Op.(*SpellOp).Chained {
		t.Error("root entry spell must take the flags payload directly")
	}
	var ifNode *Node
	for _, n := range g.Nodes {
		if _, ok := n.Op.(*IfOp); ok {
			ifNode = n
		}
	}
	if ifNode == nil {
		t.Fatal("no if node built")
	}
	if !ifNode.Op.(*IfOp).Then.Nodes[0].Op.(*SpellOp).Chained {
		t.Error("branch entry spell without params must adapt its seed as a chained input")
	}
}

func TestBuildPipeline_ExplicitPrintDisablesAutoPrint(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Steps: []ir.Step{
		{Spell: "a", Id: "res"},
		{Print: "res.value"},
	}}, env)

	if len(g.Nodes) != 2 {
		t.Fatalf("nodes = %v, want exactly the declared steps (no auto-print)", nodeIDs(g))
	}
}

func TestBuildPipeline_GraphDiamondEdges(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "ship", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "checkout", Id: "src"},
		{Spell: "test", Id: "unit", Params: map[string]any{"tree": "src.path"}},
		{Spell: "lint", Id: "style", Params: map[string]any{"tree": "src.path"}},
		{Spell: "package", Id: "image", Params: map[string]any{"tree": "src.path", "passed": "unit.ok", "clean": "style.ok"}},
		{Print: "image.done"},
	}}, env)

	if n := nodeByID(t, g, "src"); n.Input.Kind != InputSeed || len(n.Deps) != 0 {
		t.Errorf("ref-less node: input %v deps %v, want Seed at the front", n.Input.Kind, n.Deps)
	}
	if n := nodeByID(t, g, "unit"); !slices.Equal(n.Deps, []string{"src"}) {
		t.Errorf("unit deps = %v, want [src]", n.Deps)
	}
	if n := nodeByID(t, g, "image"); !slices.Equal(n.Deps, []string{"src", "style", "unit"}) {
		t.Errorf("join deps = %v, want [src style unit]", n.Deps)
	}
}

func TestBuildPipeline_GraphBareRefIsEdge(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "a", Id: "src"},
		{Spell: "b", Id: "user", Params: map[string]any{"tree": "src", "name": "not-a-binding"}},
		{Print: "user"},
	}}, env)

	if n := nodeByID(t, g, "user"); !slices.Equal(n.Deps, []string{"src"}) {
		t.Errorf("deps = %v, want bare ref src as an edge and the literal ignored", n.Deps)
	}
}

func TestBuildPipeline_GraphPrintsSerialized(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "a", Id: "x"},
		{Spell: "b", Id: "y"},
		{Print: "x"},
		{Print: "y"},
	}}, env)

	var prints []*Node
	for _, n := range g.Nodes {
		if _, ok := n.Op.(*PrintOp); ok {
			prints = append(prints, n)
		}
	}
	if len(prints) != 2 {
		t.Fatalf("print nodes = %d, want 2", len(prints))
	}
	if !slices.Contains(prints[1].Deps, prints[0].ID) {
		t.Errorf("second print deps = %v, want serialization edge on %s", prints[1].Deps, prints[0].ID)
	}
}

func TestBuildPipeline_BranchModeInheritanceAndOverride(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "gate", Id: "gate"},
		{If: "gate.ok", Then: []ir.Step{ // inherits graph
			{Spell: "t1", Id: "t1"},
			{Spell: "t2", Id: "t2"},
		}},
		{If: "gate.ok", Mode: ir.ModePipe, Then: []ir.Step{ // overrides to pipe
			{Spell: "p1"},
			{Spell: "p2"},
		}},
	}}, env)

	var ifNodes []*Node
	for _, n := range g.Nodes {
		if _, ok := n.Op.(*IfOp); ok {
			ifNodes = append(ifNodes, n)
		}
	}
	if len(ifNodes) != 2 {
		t.Fatalf("if nodes = %d, want 2", len(ifNodes))
	}
	// Both if-nodes read gate.ok, so both must wait on gate.
	for _, n := range ifNodes {
		if !slices.Contains(n.Deps, "gate") {
			t.Errorf("if node %s deps = %v, want gate from condition ref", n.ID, n.Deps)
		}
	}

	inherited := ifNodes[0].Op.(*IfOp).Then
	if len(inherited.Nodes[0].Deps) != 0 || len(inherited.Nodes[1].Deps) != 0 {
		t.Error("inherited graph branch: independent spells must have no edges between them")
	}
	overridden := ifNodes[1].Op.(*IfOp).Then
	if !slices.Equal(overridden.Nodes[1].Deps, []string{overridden.Nodes[0].ID}) {
		t.Errorf("pipe-overridden branch: second node deps = %v, want chain on first", overridden.Nodes[1].Deps)
	}
}

func TestBuildPipeline_GraphBranchFreeRefsBecomeIfDeps(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)
	g := mustBuild(t, &ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "a", Id: "gate"},
		{Spell: "b", Id: "data"},
		{If: "gate.ok", Then: []ir.Step{
			{Spell: "use", Params: map[string]any{"v": "data.val"}}, // free ref to sibling
			{Let: "inner", Value: "1 > 0"},
			{Spell: "own", Params: map[string]any{"v": "inner"}}, // branch-bound, not free
		}},
	}}, env)

	var ifNode *Node
	for _, n := range g.Nodes {
		if _, ok := n.Op.(*IfOp); ok {
			ifNode = n
		}
	}
	if ifNode == nil {
		t.Fatal("no if node built")
	}
	if !slices.Contains(ifNode.Deps, "gate") || !slices.Contains(ifNode.Deps, "data") {
		t.Errorf("if deps = %v, want condition ref gate and branch free ref data", ifNode.Deps)
	}
	if len(ifNode.Deps) != 2 {
		t.Errorf("if deps = %v: branch-internal binding must not create an edge", ifNode.Deps)
	}
}

func TestBuildPipeline_Errors(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(nil, nil, &calls)

	for _, tc := range []struct {
		name string
		p    *ir.Pipeline
		want string
	}{
		{"empty", &ir.Pipeline{Command: "r"}, "no steps"},
		{"first not spell", &ir.Pipeline{Command: "r", Steps: []ir.Step{{Let: "x", Value: "1"}}}, "first step must be a spell"},
		{"unknown mode", &ir.Pipeline{Command: "r", Mode: "parallel", Steps: []ir.Step{{Spell: "a"}}}, "unknown mode"},
		{"mode on spell", &ir.Pipeline{Command: "r", Steps: []ir.Step{{Spell: "a", Mode: ir.ModePipe}}}, "only valid on rituals and if-steps"},
		{"empty then", &ir.Pipeline{Command: "r", Steps: []ir.Step{{Spell: "a"}, {If: "true", Then: nil}}}, "must be non-empty"},
		{
			"graph cycle",
			&ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
				{Spell: "s", Id: "a", Params: map[string]any{"v": "b.x"}},
				{Spell: "s", Id: "b", Params: map[string]any{"v": "a.x"}},
			}},
			"cycle",
		},
		{
			"graph duplicate binding",
			&ir.Pipeline{Command: "r", Mode: ir.ModeGraph, Steps: []ir.Step{
				{Spell: "s", Id: "x"},
				{Let: "x", Value: "1 > 0"},
			}},
			"bound by both",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := BuildPipeline(tc.p, env); err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
		})
	}
}

func TestExecute_PipeLetIfPrint(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(map[string]any{
		"get_status": map[string]any{"ok": true, "n": 2.0},
	}, nil, &calls)

	g := mustBuild(t, &ir.Pipeline{Command: "maybe", Steps: []ir.Step{
		{Spell: "get_status", Id: "check"},
		{Let: "big", Value: "check.n > 1"},
		{If: "big",
			Then: []ir.Step{{Print: "check.n"}},
			Else: []ir.Step{{Print: `"small"`}}},
	}}, env)

	if _, err := Run(context.Background(), g, nil); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(calls.prints, []any{2.0}) {
		t.Errorf("prints = %v, want [2]", calls.prints)
	}
}

func TestExecute_GraphDiamondJoins(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(map[string]any{
		"checkout": map[string]any{"path": "/src"},
		"test":     map[string]any{"ok": true},
		"lint":     map[string]any{"ok": true},
		"package":  map[string]any{"done": true},
	}, nil, &calls)

	g := mustBuild(t, &ir.Pipeline{Command: "ship", Mode: ir.ModeGraph, Steps: []ir.Step{
		{Spell: "checkout", Id: "src"},
		{Spell: "test", Id: "unit", Params: map[string]any{"tree": "src.path"}},
		{Spell: "lint", Id: "style", Params: map[string]any{"tree": "src.path"}},
		{Spell: "package", Id: "image", Params: map[string]any{"tree": "src.path", "passed": "unit.ok", "clean": "style.ok"}},
		{Print: "image.done"},
	}}, env)

	if _, err := Run(context.Background(), g, nil); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(calls.prints, []any{true}) {
		t.Errorf("prints = %v, want [true]", calls.prints)
	}
	want := map[string]any{"tree": "/src", "passed": true, "clean": true}
	got := calls.payloads["package"]
	for k, v := range want {
		if got[k] != v {
			t.Errorf("join payload[%s] = %v, want %v (full: %v)", k, got[k], v, got)
		}
	}
}

func TestExecute_ChainAdaptsPositionalList(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(
		map[string]any{
			"pair": []any{1.0, 2.0},
			"add":  3.0,
		},
		map[string][]ir.Param{
			"add": {{Name: "x"}, {Name: "y"}},
		},
		&calls,
	)

	g := mustBuild(t, &ir.Pipeline{Command: "sum", Steps: []ir.Step{
		{Spell: "pair"},
		{Spell: "add"},
	}}, env)

	if _, err := Run(context.Background(), g, nil); err != nil {
		t.Fatal(err)
	}
	if got := calls.payloads["add"]; got["x"] != 1.0 || got["y"] != 2.0 {
		t.Errorf("add payload = %v, want positional unpack x:1 y:2", got)
	}
	if !slices.Equal(calls.prints, []any{3.0}) {
		t.Errorf("prints = %v, want the auto-printed tail [3]", calls.prints)
	}
}

func TestBuildFunction_SpellIsOneNodePlusPrint(t *testing.T) {
	var calls fakeCalls
	env := fakeEnv(map[string]any{"greet": "hello"}, nil, &calls)

	fn, _ := env.ResolveSpell("greet")
	g := BuildFunction(fn, env)
	if len(g.Nodes) != 2 {
		t.Fatalf("nodes = %v, want spell + print", nodeIDs(g))
	}

	out, err := Run(context.Background(), g, map[string]any{"name": "james"})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(calls.prints, []any{"hello"}) {
		t.Errorf("prints = %v, want [hello]", calls.prints)
	}
	if out != "hello" {
		t.Errorf("out = %v, want the print node's passthrough", out)
	}
	if got := calls.payloads["greet"]; got["name"] != "james" {
		t.Errorf("payload = %v, want the seed flags", got)
	}
}
