package graph

import (
	"fmt"
	"sort"

	expr "github.com/jlkendrick/grimoire/internal/expr"
	ir "github.com/jlkendrick/grimoire/internal/ir"
)

// BuildFunction compiles a bare spell invocation into the one-node graph
// plus its autogenerated print — the single-node case of the pipe rule,
// so spells need no output semantics of their own.
func BuildFunction(fn *ir.Function, env Env) *Graph {
	spell := &Node{
		ID:    fn.CommandName,
		Input: InputSpec{Kind: InputSeed},
		Op:    &SpellOp{Fn: fn, Runner: env.RunSpell},
	}
	printNode := &Node{
		ID:    "print#0",
		Deps:  []string{spell.ID},
		Input: InputSpec{Kind: InputChain},
		Op:    &PrintOp{Present: env.Present},
	}
	return &Graph{Nodes: []*Node{spell, printNode}, Out: printNode.ID}
}

// BuildPipeline compiles a pipeline into an executable Graph. All mode
// semantics live here: a pipe scope becomes a chain, a graph scope becomes
// the DAG its references imply, and the executor never learns which was
// which. Errors from here are validation errors — the reconciler calls
// this at scroll load (discarding the graph) so the same code both
// validates and builds.
//
// Output rule: implicitness is a pipe privilege. A pipe-rooted pipeline
// with no print step anywhere gets an autogenerated print on its tail
// (today's behavior, and what makes a bare spell just the one-node case).
// Graph scopes require explicit prints — "the tail" doesn't exist there.
func BuildPipeline(p *ir.Pipeline, env Env) (*Graph, error) {
	if len(p.Steps) == 0 {
		return nil, fmt.Errorf("pipeline %s has no steps", p.Command)
	}
	if p.Steps[0].Kind() != "spell" {
		return nil, fmt.Errorf("pipeline %s: first step must be a spell", p.Command)
	}
	mode, err := effectiveMode(p.Mode, ir.ModePipe)
	if err != nil {
		return nil, fmt.Errorf("pipeline %s: %w", p.Command, err)
	}

	b := &builder{env: env}
	g, err := b.scope(p.Steps, mode, true)
	if err != nil {
		return nil, fmt.Errorf("pipeline %s: %w", p.Command, err)
	}
	if mode == ir.ModePipe && !hasPrint(p.Steps) {
		autoPrint := &Node{
			ID:    b.syntheticID("print"),
			Deps:  []string{g.Out},
			Input: InputSpec{Kind: InputChain},
			Op:    &PrintOp{Present: env.Present},
		}
		g.Nodes = append(g.Nodes, autoPrint)
		g.Out = autoPrint.ID
	}
	return g, nil
}

type builder struct {
	env Env
	n   int // synthetic-id counter, shared across scopes for readable uniqueness
}

func (b *builder) syntheticID(label string) string {
	b.n++
	return fmt.Sprintf("%s#%d", label, b.n)
}

// scope compiles one step list. root marks the pipeline's top-level
// scope, whose seed is the CLI-flags payload; branch scopes are seeded
// with an upstream value instead (see pipeScope).
func (b *builder) scope(steps []ir.Step, mode ir.Mode, root bool) (*Graph, error) {
	if mode == ir.ModeGraph {
		return b.graphScope(steps)
	}
	return b.pipeScope(steps, root)
}

// node builds the mode-independent part of a step: its op (recursing into
// branch scopes for if-steps) and its id. Input specs and deps are the
// calling scope's business.
func (b *builder) node(step ir.Step, scopeMode ir.Mode) (*Node, error) {
	if step.Mode != "" && step.Kind() != "if" {
		return nil, fmt.Errorf("mode: is only valid on rituals and if-steps, found on a %s-step", step.Kind())
	}

	switch step.Kind() {
	case "spell":
		fn, err := b.env.ResolveSpell(step.Spell)
		if err != nil {
			return nil, err
		}
		id := step.Id
		if id == "" {
			id = b.syntheticID(step.Spell)
		}
		return &Node{ID: id, Op: &SpellOp{Fn: fn, Id: step.Id, Runner: b.env.RunSpell}}, nil

	case "if":
		if len(step.Then) == 0 {
			return nil, fmt.Errorf("if %q: then: must be non-empty", step.If)
		}
		branchMode, err := effectiveMode(step.Mode, scopeMode)
		if err != nil {
			return nil, err
		}
		then, err := b.scope(step.Then, branchMode, false)
		if err != nil {
			return nil, err
		}
		var els *Graph
		if len(step.Else) > 0 {
			if els, err = b.scope(step.Else, branchMode, false); err != nil {
				return nil, err
			}
		}
		return &Node{ID: b.syntheticID("if"), Op: &IfOp{Cond: step.If, Then: then, Else: els}}, nil

	case "let":
		return &Node{ID: b.syntheticID("let"), Op: &LetOp{Name: step.Let, Expr: step.Value}}, nil

	case "print":
		return &Node{ID: b.syntheticID("print"), Op: &PrintOp{Expr: step.Print, Present: b.env.Present}}, nil
	}
	return nil, fmt.Errorf("unknown step kind %q", step.Kind())
}

// pipeScope compiles a step list to a chain: every node depends on its
// predecessor, data flows through Chain inputs unless a spell declares
// explicit params, and the scope's result is its tail.
//
// A branch scope's seed is the if-node's input — an upstream step's
// return value, not a flags payload — so a branch-entry spell without
// params adapts it exactly like a chained input (the linear engine's
// "prev_result continues into the branch" rule). Only the root scope's
// entry receives a direct payload map.
func (b *builder) pipeScope(steps []ir.Step, root bool) (*Graph, error) {
	g := &Graph{}
	prev := ""
	for _, step := range steps {
		n, err := b.node(step, ir.ModePipe)
		if err != nil {
			return nil, err
		}

		switch {
		case step.Kind() == "spell" && len(step.Params) > 0:
			n.Input = InputSpec{Kind: InputParams, Params: step.Params}
		case prev == "":
			n.Input = InputSpec{Kind: InputSeed}
		default:
			n.Input = InputSpec{Kind: InputChain}
		}
		if prev != "" {
			n.Deps = []string{prev}
		}
		if sp, ok := n.Op.(*SpellOp); ok {
			sp.Chained = n.Input.Kind == InputChain || (n.Input.Kind == InputSeed && !root)
		}

		g.Nodes = append(g.Nodes, n)
		prev = n.ID
	}
	g.Out = prev
	return g, nil
}

// graphScope compiles a step list to the DAG its references imply. Edges
// are derived, never declared: a step depends on every sibling whose
// binding it reads. Declaration order stops mattering — except for prints,
// which are serialized in declaration order so output stays deterministic
// while spells still parallelize.
func (b *builder) graphScope(steps []ir.Step) (*Graph, error) {
	nodes := make([]*Node, 0, len(steps))
	writers := make(map[string]string) // binding name → node id
	var prints []*Node

	for _, step := range steps {
		n, err := b.node(step, ir.ModeGraph)
		if err != nil {
			return nil, err
		}

		if step.Kind() == "spell" {
			if len(step.Params) > 0 {
				n.Input = InputSpec{Kind: InputParams, Params: step.Params}
			} else {
				// No references: the node reads the pipeline seed and is
				// scheduled at the front.
				n.Input = InputSpec{Kind: InputSeed}
			}
		}

		var name string
		switch step.Kind() {
		case "spell":
			name = step.Id
		case "let":
			name = step.Let
		}
		if name != "" {
			if prior, dup := writers[name]; dup {
				return nil, fmt.Errorf("graph scope: %q is bound by both %s and %s — rebinding is ambiguous when order is derived", name, prior, n.ID)
			}
			writers[name] = n.ID
		}
		if step.Kind() == "print" {
			prints = append(prints, n)
		}
		nodes = append(nodes, n)
	}

	for i, step := range steps {
		refs, err := b.readRefs(step, writers)
		if err != nil {
			return nil, err
		}
		for _, root := range refs {
			if writer, ok := writers[root]; ok {
				nodes[i].Deps = appendUnique(nodes[i].Deps, writer)
			}
		}
	}

	for i := 1; i < len(prints); i++ {
		prints[i].Deps = appendUnique(prints[i].Deps, prints[i-1].ID)
	}

	g := &Graph{Nodes: nodes}
	if err := checkAcyclic(g); err != nil {
		return nil, err
	}
	g.Out = uniqueSink(g)
	return g, nil
}

// readRefs collects the sibling binding names a step reads — its read-set
// for edge derivation.
func (b *builder) readRefs(step ir.Step, writers map[string]string) ([]string, error) {
	switch step.Kind() {
	case "spell":
		var roots []string
		for _, v := range step.Params {
			// A bare string that names a sibling binding is a reference.
			// The runtime resolver treats it as one, so the builder must
			// too, or the edge is missed and the step races its data.
			if s, ok := v.(string); ok {
				if root := expr.ReferenceRoot(s); writers[root] != "" {
					roots = append(roots, root)
				}
			}
		}
		sort.Strings(roots) // map iteration order must not shape the graph
		return roots, nil
	case "let":
		return exprRoots(step.Value)
	case "print":
		return exprRoots(step.Print)
	case "if":
		roots, err := exprRoots(step.If)
		if err != nil {
			return nil, err
		}
		// A branch cannot start before the outer bindings it reads exist,
		// so the branches' free references are the if-node's deps too.
		for _, branch := range [][]ir.Step{step.Then, step.Else} {
			free, err := freeRefs(branch, writers)
			if err != nil {
				return nil, err
			}
			roots = append(roots, free...)
		}
		return roots, nil
	}
	return nil, nil
}

func exprRoots(src string) ([]string, error) {
	parsed, err := expr.ParseCondition(src)
	if err != nil {
		return nil, fmt.Errorf("parse %q: %w", src, err)
	}
	return expr.RootRefs(parsed), nil
}

// freeRefs returns the references a branch subtree reads that are bound by
// the enclosing scope's writers rather than within the branch itself.
func freeRefs(steps []ir.Step, writers map[string]string) ([]string, error) {
	refs, err := refsInSubtree(steps)
	if err != nil {
		return nil, err
	}
	bound := make(map[string]bool)
	boundInSubtree(steps, bound)

	var out []string
	for _, root := range refs {
		if root != "" && !bound[root] && writers[root] != "" {
			out = append(out, root)
		}
	}
	return out, nil
}

func refsInSubtree(steps []ir.Step) ([]string, error) {
	var out []string
	for _, s := range steps {
		switch s.Kind() {
		case "spell":
			for _, v := range s.Params {
				if str, ok := v.(string); ok {
					out = append(out, expr.ReferenceRoot(str))
				}
			}
		case "let":
			roots, err := exprRoots(s.Value)
			if err != nil {
				return nil, err
			}
			out = append(out, roots...)
		case "print":
			roots, err := exprRoots(s.Print)
			if err != nil {
				return nil, err
			}
			out = append(out, roots...)
		case "if":
			roots, err := exprRoots(s.If)
			if err != nil {
				return nil, err
			}
			out = append(out, roots...)
			for _, branch := range [][]ir.Step{s.Then, s.Else} {
				roots, err := refsInSubtree(branch)
				if err != nil {
					return nil, err
				}
				out = append(out, roots...)
			}
		}
	}
	return out, nil
}

func boundInSubtree(steps []ir.Step, bound map[string]bool) {
	for _, s := range steps {
		switch s.Kind() {
		case "spell":
			if s.Id != "" {
				bound[s.Id] = true
			}
		case "let":
			bound[s.Let] = true
		case "if":
			boundInSubtree(s.Then, bound)
			boundInSubtree(s.Else, bound)
		}
	}
}

func effectiveMode(m, parent ir.Mode) (ir.Mode, error) {
	switch m {
	case "":
		return parent, nil
	case ir.ModePipe, ir.ModeGraph:
		return m, nil
	}
	return "", fmt.Errorf("unknown mode %q (want %q or %q)", m, ir.ModePipe, ir.ModeGraph)
}

func hasPrint(steps []ir.Step) bool {
	for _, s := range steps {
		switch s.Kind() {
		case "print":
			return true
		case "if":
			if hasPrint(s.Then) || hasPrint(s.Else) {
				return true
			}
		}
	}
	return false
}

// checkAcyclic runs Kahn's algorithm to completion at build time so cycles
// surface as scroll-load errors, not runtime ones.
func checkAcyclic(g *Graph) error {
	indeg := make(map[string]int, len(g.Nodes))
	dependents := make(map[string][]string)
	var queue []string
	for _, n := range g.Nodes {
		indeg[n.ID] = len(n.Deps)
		for _, d := range n.Deps {
			dependents[d] = append(dependents[d], n.ID)
		}
	}
	for _, n := range g.Nodes {
		if indeg[n.ID] == 0 {
			queue = append(queue, n.ID)
		}
	}
	processed := 0
	for len(queue) > 0 {
		id := queue[0]
		queue = queue[1:]
		processed++
		for _, dep := range dependents[id] {
			if indeg[dep]--; indeg[dep] == 0 {
				queue = append(queue, dep)
			}
		}
	}
	if processed != len(g.Nodes) {
		var stuck []string
		for _, n := range g.Nodes {
			if indeg[n.ID] > 0 {
				stuck = append(stuck, n.ID)
			}
		}
		return fmt.Errorf("dependency cycle among steps %v", stuck)
	}
	return nil
}

// uniqueSink returns the id of the scope's single sink (no dependents), or
// "" when there are several — in which case the scope has no chainable
// result and consumers must use explicit references.
func uniqueSink(g *Graph) string {
	hasDependent := make(map[string]bool)
	for _, n := range g.Nodes {
		for _, d := range n.Deps {
			hasDependent[d] = true
		}
	}
	sink := ""
	for _, n := range g.Nodes {
		if !hasDependent[n.ID] {
			if sink != "" {
				return ""
			}
			sink = n.ID
		}
	}
	return sink
}

func appendUnique(list []string, v string) []string {
	for _, x := range list {
		if x == v {
			return list
		}
	}
	return append(list, v)
}
