package graph

import (
	"context"
	"fmt"

	expr "github.com/jlkendrick/grimoire/internal/expr"
)

// IfOp evaluates its condition against the current bindings and executes
// the chosen branch through the same scheduler. Both branches are built at
// construction time — runtime only chooses between prebuilt graphs. The
// if-node's own input seeds the branch, so a pipe branch chains from
// whatever preceded the if, exactly like the linear engine's
// "prev_result continues into the branch" rule.
//
// Conditions are reparsed per run for now; the builder will pre-parse once
// it exists.
type IfOp struct {
	Cond string
	Then *Graph
	Else *Graph // nil when the ritual declares no else
}

func (op *IfOp) Run(ctx context.Context, in any, ex *Exec) (any, error) {
	parsed, err := expr.ParseCondition(op.Cond)
	if err != nil {
		return nil, fmt.Errorf("parse condition %q: %w", op.Cond, err)
	}
	cond, err := expr.EvaluateCondition(parsed, ex.Bindings())
	if err != nil {
		return nil, fmt.Errorf("evaluate condition %q: %w", op.Cond, err)
	}

	branch := op.Then
	if !cond {
		branch = op.Else
	}
	if branch == nil {
		// No branch ran: pass the input through so a chained successor
		// still sees the pre-if result.
		return in, nil
	}
	out, err := ex.Run(ctx, branch, in)
	if err != nil {
		return nil, err
	}
	if branch.Out == "" {
		// The branch has no single result (multi-sink graph scope); keep
		// the chain intact rather than yielding nil.
		return in, nil
	}
	return out, nil
}

// LetOp evaluates an expression against the current bindings and publishes
// the result under Name. Its output is its input, untouched: a let sitting
// between two piped spells must not break the pipe.
type LetOp struct {
	Name string
	Expr string
}

func (op *LetOp) Run(_ context.Context, in any, ex *Exec) (any, error) {
	parsed, err := expr.ParseCondition(op.Expr)
	if err != nil {
		return nil, fmt.Errorf("parse let %q value %q: %w", op.Name, op.Expr, err)
	}
	val, err := expr.EvaluateExpression(parsed, ex.Bindings())
	if err != nil {
		return nil, fmt.Errorf("evaluate let %q: %w", op.Name, err)
	}
	ex.Bind(op.Name, val)
	return in, nil
}

// PrintOp declares a ritual output. Expr names what to print (same
// grammar as let values); when empty — the autogenerated print a pipe
// ritual or bare spell gets — the chained input is printed instead.
// Presentation itself is frontend-supplied: the CLI injects
// stdout-printing, a REST handler collects values into a response, tests
// capture. The input always passes through so a print step is transparent
// to the pipe.
type PrintOp struct {
	Expr    string
	Present func(v any) error
}

func (op *PrintOp) Run(_ context.Context, in any, ex *Exec) (any, error) {
	val := in
	if op.Expr != "" {
		parsed, err := expr.ParseCondition(op.Expr)
		if err != nil {
			return nil, fmt.Errorf("parse print %q: %w", op.Expr, err)
		}
		val, err = expr.EvaluateExpression(parsed, ex.Bindings())
		if err != nil {
			return nil, fmt.Errorf("evaluate print %q: %w", op.Expr, err)
		}
	}
	if op.Present != nil {
		// An autogenerated print (no Expr) is a convenience: it skips a
		// nil return so side-effect spells don't dump "null". An
		// explicit print: is a contract and prints null faithfully.
		if op.Expr == "" && val == nil {
			return in, nil
		}
		if err := op.Present(val); err != nil {
			return nil, err
		}
	}
	return in, nil
}
